---
title: "Recruiting a PhD Student"
author: |
  | Matthew Ross
  | Colorado State University
date: "9/17/2019"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

I'm very happy to start recruiting a fully-funded PhD student (5 years of funding).
This student will work on an NSF Macrosystems project to integrate watershed ecosystem
data across a variety of data sources (including the Critical Zone Observator,
Long-Term Ecological Research stations, National Ecological Observation Network,
the United States Geological Survey, and the Forest Service). We will be working 
with [Emily Bernhardt](https://bernhardtlab.weebly.com/) at Duke University and the team
will be a mix of data scientists and watersehd biogeochemists at Duke and CSU.
We will be using this data to push watershed science to a continental scale research 
endeavor and 
to ask questions about how watershed-ecosystems have changed over the past 50 years
across the country. The ideal candidate will have a background in both R and 
watershed science. This project also has a substantial mission to build and 
develop tools for others to use to make watershed science easier to do and the
student should be enthusiastic about open science and building a more inclusive
community around watershed research. Please contact me if interested.

The NSF abstract is pasted below for more information:


This research will enable anyone with internet access to compare the flow and the chemistry of hundreds of streams throughout the United States and to explore their watersheds. The project will combine data sets from many separate research projects into an attractive Web site that makes the data available. This will make it easy for scientists and students to ask questions about water quality and river flow patterns across the continent. Researchers will use these data to study what types of watersheds are best at retaining nutrients, are recovering most rapidly from decades of acid rain, have the highest erosion rates, and have flow patterns that are least sensitive to floods and droughts. The lessons we learn from studying many watersheds and streams will contribute to more effective management of our nation's water and forest resources.

Much of the literature of watershed ecosystem science over the last decade has focused on gaining ever finer detail of spatial heterogeneity within watersheds. This fine-scale focus has identified many idiosyncrasies of individual watersheds but has not helped us develop general theories about watershed dynamics. Most watershed ecosystem studies remain rather parochial, involving detailed studies of individual or paired watersheds, or surveys of a small set of attributes across multiple watersheds. Macrosystem watershed science, or the search for general principles that describe the functional capacity and behavior across watersheds, has been limited. A major reason for this lack of large-scale focus is the challenge of data access and integration across sites. Our goal in this proposal is to create a synthetic dataset that merges all US watershed ecosystem studies into a common platform (MacroSheds) and to enable and train a new generation of watershed ecosystem scientists in the art and practice of macroscale watershed ecosystem science.