---
title: ""
output:
  html_document:
    css:  index.css
---


<br>

#### I'm an ecosystem/watershed scientist in Colorado State's
#### [Ecosystem Science and Sustainability department](https://warnercnr.colostate.edu/ess/).
#### My broadest research goals are best captured by a quote from
#### the landscape architect John Tillman Lyle in 1985 when he said: 

<br>

#####  The point is that if we are going to design ecosystems,
#####  and we continually do so whether we care to face
#####  all of the implications or not, then it will be best
#####  to design them intentionally, making use of all 
#####  the ecological understanding we can bring to bear.

<br>

####  Towards this goal, I hope to work with students and
####  collaborators to answer these types of questions:

<br>


####  **1) How do people reshape and change landscapes?**

<br>

####  **2) What are the dominant drivers and feedbacks that structure**
####  **these landscapes, and how do they influence downstream ecosystems**

<br>

####  **3) Can we use knowledge from 1&2 to design ecosystems better?**

<br>
<br>
<br>
<br>



