---
title: ""
output:
  html_document:
    css:  research.css
---
<br>
<br>

####  I use ideas from geomorphology, hydrology, and
####  ecology to understand how humans [alter ecosystems](http://www.annualreviews.org/doi/abs/10.1146/annurev-environ-121012-100957).
####  As a PhD student at Duke University, I worked with my advisers
####  [Emily Bernhardt](http://bernhardtlab.weebly.com/), [Martin Doyle](http://sites.nicholas.duke.edu/martindoyle/), and [Brian McGlynn](http://www.mcglynnlab.com/)
####  to understand how mountaintop mining for coal
####  has changed the [physical landscape](http://pubs.acs.org/doi/full/10.1021/acs.est.5b04532) in Central Appalachia
####  and how these changes lead to long-term and dramatic 
####  shifts in [hydrologic](https://pubs.acs.org/doi/abs/10.1021/acs.est.7b02288) and [biogeochemical](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2017GB005798) regimes and changes
####  in local and regional water quality. As a post-doctoral researcher
####  at UNC Chapel Hill, I worked with Tamlin Pavelsky on
####  multi-spectral remote sensing techniques
####  to understand water quality changes at regional to global scales. 
####  More of my research can be found on my [Google Scholar page](https://scholar.google.com/citations?user=FjuxZdYAAAAJ&hl=en&oi=ao)
 
<br>
<br>

### *Current projects I'm most excited about*

<br>

#### 1) Remote sensing of water quality and ecological controls on longitudinal variation in river chemistry.

#### 2) Using otolith's (inner ear bones of fish) to recreate and understand historic change in 
#### metal concentrations in lakes and reservoirs.

#### 3) Understanding how people have altered chemical weathering across the globe.

#### 4) Linking the combined impacts of fire, agriculture, and mining on
####  water quality trends in the state of Colorado and the western USA. 

